# Generated by Django 4.2.5 on 2023-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_fees',
            field=models.IntegerField(),
        ),
    ]
